import discord # type: ignore
from discord.ext import commands, tasks
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from apscheduler.triggers.cron import CronTrigger
import asyncio
import logging
import os
from dotenv import load_dotenv

load_dotenv()

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')


intents = discord.Intents.default()
intents.message_content = True  
bot = commands.Bot(command_prefix='bwa', intents=intents)

scheduler = AsyncIOScheduler()  

notifications = [
    {"time": "23:45:00", "days": ["tue", "thu", "wed"], "sound": "Kano - 【Rabinva】Stella-rium by Geomacher on Smule- Social Singing Karaoke App_5(2).mp3"},
  
]

# Waktu masuk dan keluar voice channel
voice_schedule = [
    {"join_time": "23:45:00", "leave_time": "23:50:00", "days": ["tue", "thu", "wed"], "voice_channel_id": 1005098144251527218},
]


async def play_sound(voice_channel_id, sound_file):
    voice_channel = bot.get_channel(voice_channel_id)
    if voice_channel is not None:
        if not bot.voice_clients:
            voice_client = await voice_channel.connect()
        else:
            voice_client = bot.voice_clients[0]
        audio_source = discord.FFmpegPCMAudio(sound_file)
        if not voice_client.is_playing():
            logging.info(f"Memutar suara {sound_file} di channel {voice_channel.name}")
            voice_client.play(audio_source)
            while voice_client.is_playing():
                await asyncio.sleep(1)


async def join_voice_channel(voice_channel_id):
    voice_channel = bot.get_channel(voice_channel_id)
    if voice_channel is not None and not bot.voice_clients:
        await voice_channel.connect()
        logging.info(f"Bot bergabung ke voice channel {voice_channel.name}")

async def leave_voice_channel(voice_channel_id):
    for vc in bot.voice_clients:
        if vc.channel.id == voice_channel_id:
            await vc.disconnect()
            logging.info(f"Bot meninggalkan voice channel {vc.channel.name}")


for notification in notifications:
    time = notification["time"]
    days = notification["days"]
    sound_file = notification["sound"]
    hour, minute, second = map(int, time.split(':'))
    for day in days:
        scheduler.add_job(play_sound, CronTrigger(day_of_week=day, hour=hour, minute=minute, second=second), args=[1189594050307825756, sound_file])

for schedule in voice_schedule:
    join_time = schedule["join_time"]
    leave_time = schedule["leave_time"]
    days = schedule["days"]
    voice_channel_id = schedule["voice_channel_id"]
    join_hour, join_minute, join_second = map(int, join_time.split(':'))
    leave_hour, leave_minute, leave_second = map(int, leave_time.split(':'))
    for day in days:
        scheduler.add_job(join_voice_channel, CronTrigger(day_of_week=day, hour=join_hour, minute=join_minute, second=join_second), args=[voice_channel_id])
        scheduler.add_job(leave_voice_channel, CronTrigger(day_of_week=day, hour=leave_hour, minute=leave_minute, second=join_second), args=[voice_channel_id])


@bot.event
async def on_ready():
    logging.info(f'Bot {bot.user} telah siap.')
    scheduler.start()
    reconnect_task.start()


@tasks.loop(seconds=60)
async def reconnect_task():
    if not bot.is_closed():
        logging.info('Bot masih terhubung dan berjalan dengan baik.')
    else:
        logging.warning('Bot terputus, mencoba untuk reconnect...')
        try:
            await bot.connect(reconnect=True)
            logging.info('Bot berhasil reconnect.')
        except Exception as e:
            logging.error(f'Reconnect gagal: {e}')
            await asyncio.sleep(5)

@bot.event
async def on_disconnect():
    logging.warning('Bot terputus, mencoba untuk reconnect...')

#JS
@bot.command(name='bosscolon')
async def bosscolon(ctx):
    embed = discord.Embed(title='Boss Colon')
    embed.add_field(name='MQ Chapter', value='1', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Land Under Development')
    embed.add_field(name='Element', value='Earth', inline=True)
    embed.add_field(name='Base HP', value='1000', inline=True)
    embed.add_field(name='Base EXP', value='3000', inline=True)
    embed.add_field(name='P.Def', value='7', inline=True)
    embed.add_field(name='M.Def', value='7', inline=True)
    embed.add_field(name='P.Res', value='0', inline=True)
    embed.add_field(name='M.Res', value='0', inline=True)
    embed.add_field(name='Prorate', value='N:15  P:10  M:10', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='11', inline=True)
    embed.add_field(name='Retaliation', value='None', inline=False)
    embed.set_footer(text='EASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='bossroga')
async def bossroga(ctx):
    embed = discord.Embed(title='Boss Roga')
    embed.add_field(name='MQ Chapter', value='3', inline=True)
    embed.add_field(name='MQ Locked', value='Yes', inline=True)
    embed.add_field(name='Map', value='Saham Underground Cave - Deepest Part')
    embed.add_field(name='Element', value='Neutral', inline=True)
    embed.add_field(name='Base HP', value='250.000', inline=True)
    embed.add_field(name='Base EXP', value='3000', inline=True)
    embed.add_field(name='P.Def', value='62\nFTS 186', inline=True)
    embed.add_field(name='M.Def', value='62\nFTS 186', inline=True)
    embed.add_field(name='P.Res', value='2\nFTS 27', inline=True)
    embed.add_field(name='M.Res', value='2\nFTS 27', inline=True)
    embed.add_field(name='Prorate', value='N:15 P:10 M:10', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='279\nFTS 93\n\n', inline=True)
    embed.add_field(name='Retaliation', value='FTS: The bosss defenses and resistances significantly increase for a\nperiod of time (~15 seconds). The boss attack power is also\nreduced during this duration.\n\n', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='excavatedgolem')
async def excavatedgolem(ctx):
    embed = discord.Embed(title='Excavated Golem')
    embed.add_field(name='MQ Chapter', value='1', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Underground Ruins: Deepest Part')
    embed.add_field(name='Element', value='Neutral', inline=True)
    embed.add_field(name='Base HP', value='3150', inline=True)
    embed.add_field(name='Base EXP', value='90', inline=True)
    embed.add_field(name='P.Def', value='12', inline=True)
    embed.add_field(name='M.Def', value='12', inline=True)
    embed.add_field(name='P.Res', value='0', inline=True)
    embed.add_field(name='M.Res', value='0', inline=True)
    embed.add_field(name='Prorate', value='N:10  P:15  M:15', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='12', inline=True)
    embed.add_field(name='Retaliation', value='None\n\nNote : Breaking the parts will reduce the boss defenses by 100%', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='eeiriecrystal')
async def eeiriecrystal(ctx):
    embed = discord.Embed(title='Eeirie Crystal')
    embed.add_field(name='MQ Chapter', value='1', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Isthmus Of Kaus: Dragons Den')
    embed.add_field(name='Element', value='Dark', inline=True)
    embed.add_field(name='Base HP', value='6.300', inline=True)
    embed.add_field(name='Base EXP', value='225', inline=True)
    embed.add_field(name='P.Def', value='0', inline=True)
    embed.add_field(name='M.Def', value='0', inline=True)
    embed.add_field(name='P.Res', value='0', inline=True)
    embed.add_field(name='M.Res', value='0', inline=True)
    embed.add_field(name='Prorate', value='N:30  P:5  M:5', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='0', inline=True)
    embed.add_field(name='Retaliation', value='None', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='minotaur')
async def minotaur(ctx):
    embed = discord.Embed(title='Minotaur')
    embed.add_field(name='MQ Chapter', value='1', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Ruined Temple: Forbidden hall')
    embed.add_field(name='Element', value='Wind', inline=True)
    embed.add_field(name='Base HP', value='18.000', inline=True)
    embed.add_field(name='Base EXP', value='420', inline=True)
    embed.add_field(name='P.Def', value='32', inline=True)
    embed.add_field(name='M.Def', value='32', inline=True)
    embed.add_field(name='P.Res', value='1', inline=True)
    embed.add_field(name='M.Res', value='1', inline=True)
    embed.add_field(name='Prorate', value='N:30  P:5  M:5', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='48', inline=True)
    embed.add_field(name='Retaliation', value='When the boss HP reaches below 20% the boss will gain 100% guard rate for 10 seconds\nand perform three long-range rush attacks that inflict ignite\n\n', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='brutaldragondecel')
async def brutaldragondecel(ctx):
    embed = discord.Embed(title='Brutal Dragon Decel')
    embed.add_field(name='MQ Chapter', value='1', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Nisel Mountain: The Top')
    embed.add_field(name='Element', value='Earth', inline=True)
    embed.add_field(name='Base HP', value='53.000', inline=True)
    embed.add_field(name='Base EXP', value='560', inline=True)
    embed.add_field(name='P.Def', value='20', inline=True)
    embed.add_field(name='M.Def', value='20', inline=True)
    embed.add_field(name='P.Res', value='1', inline=True)
    embed.add_field(name='M.Res', value='1', inline=True)
    embed.add_field(name='Prorate', value='N:5  P:20  M:20', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='75', inline=True)
    embed.add_field(name='Retaliation', value='T : Guard rate up for 12 seconds\n', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='warmonger')
async def warmonger(ctx):
    embed = discord.Embed(title='Warmonger')
    embed.add_field(name='MQ Chapter', value='2', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Haotas Ravine: Deepest Part')
    embed.add_field(name='Element', value='Light', inline=True)
    embed.add_field(name='Base HP', value='147.690', inline=True)
    embed.add_field(name='Base EXP', value='960', inline=True)
    embed.add_field(name='P.Def', value='60', inline=True)
    embed.add_field(name='M.Def', value='60', inline=True)
    embed.add_field(name='P.Res', value='2', inline=True)
    embed.add_field(name='M.Res', value='2', inline=True)
    embed.add_field(name='Prorate', value='N:150  P:1  M:1', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='45', inline=True)
    embed.add_field(name='Retaliation', value='None', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='forestia')
async def forestia(ctx):
    embed = discord.Embed(title='Forestia')
    embed.add_field(name='MQ Chapter', value='2', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Land Of Chaos')
    embed.add_field(name='Element', value='Wind', inline=True)
    embed.add_field(name='Base HP', value='135.000', inline=True)
    embed.add_field(name='Base EXP', value='1480', inline=True)
    embed.add_field(name='P.Def', value='24', inline=True)
    embed.add_field(name='M.Def', value='24', inline=True)
    embed.add_field(name='P.Res', value='1', inline=True)
    embed.add_field(name='M.Res', value='1', inline=True)
    embed.add_field(name='Prorate', value='N:15  P:10  M:10', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='292', inline=True)
    embed.add_field(name='Retaliation', value='The players can fall off the stages cliffs.', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='ancientempress')
async def ancientempress(ctx):
    embed = discord.Embed(title='Ancient Empress')
    embed.add_field(name='MQ Chapter', value='3', inline=True)
    embed.add_field(name='MQ Locked', value='Yes (Area Lock)', inline=True)
    embed.add_field(name='Map', value='Ancient Empress Tomb: Deepest Part')
    embed.add_field(name='Element', value='Light', inline=True)
    embed.add_field(name='Base HP', value='130.000', inline=True)
    embed.add_field(name='Base EXP', value='3.120', inline=True)
    embed.add_field(name='P.Def', value='32', inline=True)
    embed.add_field(name='M.Def', value='32', inline=True)
    embed.add_field(name='P.Res', value='52', inline=True)
    embed.add_field(name='M.Res', value='52', inline=True)
    embed.add_field(name='Prorate', value='N:15  P:10  M:10', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='48', inline=True)
    embed.add_field(name='Retaliation', value='None', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='flarevolg')
async def flarevolg(ctx):
    embed = discord.Embed(title='Flare Volg')
    embed.add_field(name='MQ Chapter', value='2', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Fiery Volcano: Boss Map')
    embed.add_field(name='Element', value='Fire', inline=True)
    embed.add_field(name='Base HP', value='120.000', inline=True)
    embed.add_field(name='Base EXP', value='1.500', inline=True)
    embed.add_field(name='P.Def', value='Ph1:100|Ph2:62', inline=True)
    embed.add_field(name='M.Def', value='Ph1:100|Ph2:62', inline=True)
    embed.add_field(name='P.Res', value='28', inline=True)
    embed.add_field(name='M.Res', value='28', inline=True)
    embed.add_field(name='Prorate', value='N:6  P:25  M:25', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='56', inline=True)
    embed.add_field(name='Retaliation', value='The boss switches to PH2 at 50% HP.\n\nNote : Breaking parts reduces the boss DEF and MDEF by 25%.', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='ganglef')
async def ganglef(ctx):
    embed = discord.Embed(title='Ganglef')
    embed.add_field(name='MQ Chapter', value='2', inline=True)
    embed.add_field(name='MQ Locked', value='Yes (Area Lock)', inline=True)
    embed.add_field(name='Map', value='Scaro Town: Deepest Part')
    embed.add_field(name='Element', value='Earth', inline=True)
    embed.add_field(name='Base HP', value='107.800', inline=True)
    embed.add_field(name='Base EXP', value='1.150', inline=True)
    embed.add_field(name='P.Def', value='232', inline=True)
    embed.add_field(name='M.Def', value='58', inline=True)
    embed.add_field(name='P.Res', value='1', inline=True)
    embed.add_field(name='M.Res', value='25', inline=True)
    embed.add_field(name='Prorate', value='N:6  P:25  M:25', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='43', inline=True)
    embed.add_field(name='Retaliation', value='None', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='gespenst')
async def gespenst(ctx):
    embed = discord.Embed(title='Gespenst')
    embed.add_field(name='Map', value='Underground Channel')
    embed.add_field(name='Element', value='Dark', inline=True)
    embed.add_field(name='Base HP', value='8.544', inline=True)
    embed.add_field(name='Base EXP', value='240', inline=True)
    embed.add_field(name='P.Def', value='26', inline=True)
    embed.add_field(name='M.Def', value='50', inline=True)
    embed.add_field(name='P.Res', value='0', inline=True)
    embed.add_field(name='M.Res', value='0', inline=True)
    embed.add_field(name='Prorate', value='N:20  P:25  M:25', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='30', inline=True)
    embed.add_field(name='Retaliation', value='None', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='forestwolf')
async def forestwolf(ctx):
    embed = discord.Embed(title='Forest Wolf')
    embed.add_field(name='MQ Chapter', value='1', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Marbaro Forest: Deepest Part')
    embed.add_field(name='Element', value='Wind', inline=True)
    embed.add_field(name='Base HP', value='16.038', inline=True)
    embed.add_field(name='Base EXP', value='300', inline=True)
    embed.add_field(name='P.Def', value='30', inline=True)
    embed.add_field(name='M.Def', value='30', inline=True)
    embed.add_field(name='P.Res', value='0', inline=True)
    embed.add_field(name='M.Res', value='0', inline=True)
    embed.add_field(name='Prorate', value='N:8  P:20  M:20', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='45', inline=True)
    embed.add_field(name='Retaliation', value='None', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='bossgoblin')
async def bossgoblin(ctx):
    embed = discord.Embed(title='Boss Goblin')
    embed.add_field(name='MQ Chapter', value='1', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Ribisco Cave: Deepest Part')
    embed.add_field(name='Element', value='Fire', inline=True)
    embed.add_field(name='Base HP', value='26.758', inline=True)
    embed.add_field(name='Base EXP', value='560', inline=True)
    embed.add_field(name='P.Def', value='30', inline=True)
    embed.add_field(name='M.Def', value='30', inline=True)
    embed.add_field(name='P.Res', value='0', inline=True)
    embed.add_field(name='M.Res', value='0', inline=True)
    embed.add_field(name='Prorate', value='N:15  P:10  M:10', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='75', inline=True)
    embed.add_field(name='Retaliation', value='None', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='mochelo')
async def mochelo(ctx):
    embed = discord.Embed(title='Mochelo')
    embed.add_field(name='MQ Chapter', value='2', inline=True)
    embed.add_field(name='MQ Locked', value='Yes', inline=True)
    embed.add_field(name='Map', value='Fiery Volcano: Area 3')
    embed.add_field(name='Element', value='Wind', inline=True)
    embed.add_field(name='Base HP', value='60.000', inline=True)
    embed.add_field(name='Base EXP', value='620', inline=True)
    embed.add_field(name='P.Def', value='0', inline=True)
    embed.add_field(name='M.Def', value='0', inline=True)
    embed.add_field(name='P.Res', value='1', inline=True)
    embed.add_field(name='M.Res', value='1', inline=True)
    embed.add_field(name='Prorate', value='N:3  P:50  M:50', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='64', inline=True)
    embed.add_field(name='Retaliation', value='None.\nThe boss attack power decreases at 50% HP and at 25% HP.', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='ooze')
async def ooze(ctx):
    embed = discord.Embed(title='Ooze')
    embed.add_field(name='MQ Chapter', value='2', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Lutaros Cavern: Deepest Part')
    embed.add_field(name='Element', value='Water', inline=True)
    embed.add_field(name='Base HP', value='44.000', inline=True)
    embed.add_field(name='Base EXP', value='1.400', inline=True)
    embed.add_field(name='P.Def', value='78', inline=True)
    embed.add_field(name='M.Def', value='78', inline=True)
    embed.add_field(name='P.Res', value='12', inline=True)
    embed.add_field(name='M.Res', value='12', inline=True)
    embed.add_field(name='Prorate', value='N:30  P:5  M:5', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='0', inline=True)
    embed.add_field(name='Retaliation', value='None', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='mauez')
async def mauez(ctx):
    embed = discord.Embed(title='Mauez')
    embed.add_field(name='MQ Chapter', value='2', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Lutaros Cavern: Deepest Part')
    embed.add_field(name='Element', value='Water', inline=True)
    embed.add_field(name='Base HP', value='86.000', inline=True)
    embed.add_field(name='Base EXP', value='1.290', inline=True)
    embed.add_field(name='P.Def', value='PH1: 165 | PH2 : 28', inline=True)
    embed.add_field(name='M.Def', value='PH1: 165 | PH2 : 28', inline=True)
    embed.add_field(name='P.Res', value='7', inline=True)
    embed.add_field(name='M.Res', value='7', inline=True)
    embed.add_field(name='Prorate', value='N:15  P:10  M:10', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='PH1 : 41 | PH2 : 246', inline=True)
    embed.add_field(name='Retaliation', value='The boss switches to PH2 at 50% HP.', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='demonsgate')
async def demonsgate(ctx):
    embed = discord.Embed(title='Demons Gate')
    embed.add_field(name='MQ Chapter', value='2', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Saham Crater')
    embed.add_field(name='Element', value='Dark', inline=True)
    embed.add_field(name='Base HP', value='18.000', inline=True)
    embed.add_field(name='Base EXP', value='1.440', inline=True)
    embed.add_field(name='P.Def', value='180', inline=True)
    embed.add_field(name='M.Def', value='180', inline=True)
    embed.add_field(name='P.Res', value='N:165 | F:28', inline=True)
    embed.add_field(name='M.Res', value='N:165 | F:28', inline=True)
    embed.add_field(name='Prorate', value='N:150  P:1  M:1', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='0', inline=True)
    embed.add_field(name='Retaliation', value='F: Guard rate up for 15 seconds', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='astol')
async def astol(ctx):
    embed = discord.Embed(title='Astol')
    embed.add_field(name='MQ Chapter', value='2', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Aulada Ancient Tower')
    embed.add_field(name='Element', value='Wind', inline=True)
    embed.add_field(name='Base HP', value='82.040', inline=True)
    embed.add_field(name='Base EXP', value='760', inline=True)
    embed.add_field(name='P.Def', value='50', inline=True)
    embed.add_field(name='M.Def', value='150', inline=True)
    embed.add_field(name='P.Res', value='1', inline=True)
    embed.add_field(name='M.Res', value='1', inline=True)
    embed.add_field(name='Prorate', value='N:6  P:25  M:25', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='112', inline=True)
    embed.add_field(name='Retaliation', value='TS: The boss will perform a delayed straight-line counter attack. Due to the delayed nature of this attack, TS is actually safe to use.\n\nNote: You can easily break this boss\'s head by interrupting it while it is slowly flying towards you with its body parallel to the ground.', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='ruingolem')
async def ruingolem(ctx):
    embed = discord.Embed(title='Ruin Golem')
    embed.add_field(name='MQ Chapter', value='2', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Zoktzda Ruins: Reversed Hall')
    embed.add_field(name='Element', value='Light', inline=True)
    embed.add_field(name='Base HP', value='41.200', inline=True)
    embed.add_field(name='Base EXP', value='660', inline=True)
    embed.add_field(name='P.Def', value='106', inline=True)
    embed.add_field(name='M.Def', value='106', inline=True)
    embed.add_field(name='P.Res', value='1', inline=True)
    embed.add_field(name='M.Res', value='1', inline=True)
    embed.add_field(name='Prorate', value='N:10  P:15  M:15', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='14', inline=True)
    embed.add_field(name='Retaliation', value='Support mobs will spawn every 20 seconds\n\nNote: Breaking parts reduces the boss DEF and MDEF by 23.8%.', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='maskedwarrior')
async def maskedwarrior(ctx):
    embed = discord.Embed(title='Masked Warrior')
    embed.add_field(name='MQ Chapter', value='3', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Land Under Cultivation: Hill')
    embed.add_field(name='Element', value='Fire', inline=True)
    embed.add_field(name='Base HP', value='276.000', inline=True)
    embed.add_field(name='Base EXP', value='4.300', inline=True)
    embed.add_field(name='P.Def', value='134', inline=True)
    embed.add_field(name='M.Def', value='134', inline=True)
    embed.add_field(name='P.Res', value='2', inline=True)
    embed.add_field(name='M.Res', value='2', inline=True)
    embed.add_field(name='Prorate', value='N:6  P:25  M:25', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='200', inline=True)
    embed.add_field(name='Retaliation', value='None.\n\nNote: Breaking parts will increase the boss movement speed.', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='pillargolem')
async def pillargolem(ctx):
    embed = discord.Embed(title='Pillar Golem')
    embed.add_field(name='MQ Chapter', value='3', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Lost Town: Magic Barrier')
    embed.add_field(name='Element', value='Earth', inline=True)
    embed.add_field(name='Base HP', value='324.000', inline=True)
    embed.add_field(name='Base EXP', value='3.600', inline=True)
    embed.add_field(name='P.Def', value='140', inline=True)
    embed.add_field(name='M.Def', value='140', inline=True)
    embed.add_field(name='P.Res', value='2', inline=True)
    embed.add_field(name='M.Res', value='2', inline=True)
    embed.add_field(name='Prorate', value='N:3  P:50  M:50', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='11', inline=True)
    embed.add_field(name='Retaliation', value='FT: If inflicted when the boss is Yellow, the boss will turn Red and become enraged (EN) for 10 seconds. While in enraged mode, the boss defenses and attack power are significantly increased and the boss does not retaliate to FTS.\nInflicting F to the boss while it is Yellow will also cause the boss to attack with a foe-centered AOE ground pound.\n\nNote: Breaking parts lowers the boss movement speed', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='yelb')
async def yelb(ctx):
    embed = discord.Embed(title='Grass Dragon Yelb')
    embed.add_field(name='MQ Chapter', value='3', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Albatif Village')
    embed.add_field(name='Element', value='Earth', inline=True)
    embed.add_field(name='Base HP', value='439.190', inline=True)
    embed.add_field(name='Base EXP', value='5.040', inline=True)
    embed.add_field(name='P.Def', value='N: 146 | SHELL: 1022', inline=True)
    embed.add_field(name='M.Def', value='N: 146 | SHELL: 657', inline=True)
    embed.add_field(name='P.Res', value='N: 2 | SHELL: 22', inline=True)
    embed.add_field(name='M.Res', value='N: 2 | SHELL: 2', inline=True)
    embed.add_field(name='Prorate', value='N:3  P:50  M:50', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='87', inline=True)
    embed.add_field(name='Retaliation', value='SLOW/STOP/IGNITE: When the boss receives a Slow or Stop ailment during normal mode, it will change to enraged mode for 30 sec and then go back to normal mode. While in enraged mode, the boss defenses are halved and the boss movement speed increases.\nDAMAGE: When the boss receives damage higher than 3% of its health in one instance, it will go into enraged mode and shell mode\n(SHELL) at the same time for 30 sec. While in shell mode, the bosses defenses increase by a lot.\nPARA/ARMORBREAK: Removes the boss shell mode and returns the defenses to normal. The boss will retaliate with a low damage, full-map AOE attack that inflicts paralysis if inflicted with Armor Break or Paralysis while in shell mode.\nWhile the boss is in enraged mode, it will perform full-map AOE attacks periodically. All of these full-map AOE attacks inflict ailments.', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='nurethoth')
async def nurethoth(ctx):
    embed = discord.Embed(title='Nurethoth')
    embed.add_field(name='MQ Chapter', value='3', inline=True)
    embed.add_field(name='MQ Locked', value='Yes', inline=True)
    embed.add_field(name='Map', value='Gate to Another World: Front')
    embed.add_field(name='Element', value='Dark', inline=True)
    embed.add_field(name='Base HP', value='500.000', inline=True)
    embed.add_field(name='Base EXP', value='5.360', inline=True)
    embed.add_field(name='P.Def', value='PH1 : 152 | PH2 : 76', inline=True)
    embed.add_field(name='M.Def', value='PH1 : 152 | PH2 : 76', inline=True)
    embed.add_field(name='P.Res', value='PH1 : 23 | PH2 : 3', inline=True)
    embed.add_field(name='M.Res', value='PH1 : 23 | PH2 : 3', inline=True)
    embed.add_field(name='Prorate', value='N:75  P:2  M:2', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='PH1 : 57 | PH2 : 285', inline=True)
    embed.add_field(name='Retaliation', value='FTS: If inflicted above 50% HP, the boss will retaliate with a high damage AOE that: flinches (if the boss was flinched), tumbles (if the boss was tumbled), or stuns (if the boss was stunned).\n\nThe boss switches to PH2 at 50% HP.', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='b.b.goblin')
async def bbgoblin(ctx):
    embed = discord.Embed(title='B.B. Goblin')
    embed.add_field(name='Map', value='Rinom Plains')
    embed.add_field(name='Element', value='Fire', inline=True)
    embed.add_field(name='Base HP', value='24.331', inline=True)
    embed.add_field(name='Base EXP', value='2.400', inline=True)
    embed.add_field(name='P.Def', value='140', inline=True)
    embed.add_field(name='M.Def', value='210', inline=True)
    embed.add_field(name='P.Res', value='1', inline=True)
    embed.add_field(name='M.Res', value='1', inline=True)
    embed.add_field(name='Prorate', value='N:15  P:10  M:10', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='157', inline=True)
    embed.add_field(name='Retaliation', value='None', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='goovua')
async def goovua(ctx):
    embed = discord.Embed(title='Goovua')
    embed.add_field(name='MQ Chapter', value='4', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Akaku Desert: Hill')
    embed.add_field(name='Element', value='Neutral', inline=True)
    embed.add_field(name='Base HP', value='400.000', inline=True)
    embed.add_field(name='Base EXP', value='500.000', inline=True)
    embed.add_field(name='P.Def', value='PH1: 41\nPH2: 57\nPH3: 82\nLHP: 0', inline=True)
    embed.add_field(name='M.Def', value='PH1: 41\nPH2: 57\nPH3: 82\nLHP: 0', inline=True)
    embed.add_field(name='P.Res', value='3', inline=True)
    embed.add_field(name='M.Res', value='3', inline=True)
    embed.add_field(name='Prorate', value='N:15  P:10  M:10', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='PH1: 246 | PH2: 273 | PH3: 308 | LPH: 0', inline=True)
    embed.add_field(name='Retaliation', value='The boss switches to PH2 30 seconds after initiating the battle. Similarly, the boss switches to PH3 30 seconds after switching to PH2. When the boss HP goes below 20%, the boss enters the LHP phase. During the LHP phase, the boss defenses are zero and the boss nonfractional damage to players is increased by approximately 10 times.', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='scrader')
async def scrader(ctx):
    embed = discord.Embed(title='Scrader')
    embed.add_field(name='MQ Chapter', value='4', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Magic Waste Site: Deepest Part')
    embed.add_field(name='Element', value='Dark', inline=True)
    embed.add_field(name='Base HP', value='660.000', inline=True)
    embed.add_field(name='Base EXP', value='7.900', inline=True)
    embed.add_field(name='P.Def', value='255', inline=True)
    embed.add_field(name='M.Def', value='255', inline=True)
    embed.add_field(name='P.Res', value='3', inline=True)
    embed.add_field(name='M.Res', value='3', inline=True)
    embed.add_field(name='Prorate', value='N:150  P:1  M:1', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='64', inline=True)
    embed.add_field(name='Retaliation', value='Dealing damage above 2% of its max HP in one instance will cause the boss to go into rage mode (Red color) for 20 seconds. While in rage mode, the boss ATK and MATK increase.', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='bkod')
async def bkod(ctx):
    embed = discord.Embed(title='Black Knight Of Delusion')
    embed.add_field(name='MQ Chapter', value='4', inline=True)
    embed.add_field(name='MQ Locked', value='Yes', inline=True)
    embed.add_field(name='Map', value='Abyss of No Return: Deepest Area')
    embed.add_field(name='Element', value='Dark', inline=True)
    embed.add_field(name='Base HP', value='540.000', inline=True)
    embed.add_field(name='Base EXP', value='6.600', inline=True)
    embed.add_field(name='P.Def', value='176', inline=True)
    embed.add_field(name='M.Def', value='176', inline=True)
    embed.add_field(name='P.Res', value='PH1:23\nPH2:33', inline=True)
    embed.add_field(name='M.Res', value='PH1:23\nPH2:33', inline=True)
    embed.add_field(name='Prorate', value='N:5  P:30  M:30', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='231', inline=True)
    embed.add_field(name='Retaliation', value='TS: Boss backs away to the left (PH1) or to the right (PH2) if inflicted.\n\nThe boss switches from PH1 to PH2 at 50% HP.', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='ecb')
async def ecb(ctx):
    embed = discord.Embed(title='Evil Crystal Beast')
    embed.add_field(name='MQ Chapter', value='4', inline=True)
    embed.add_field(name='MQ Locked', value='Yes', inline=True)
    embed.add_field(name='Map', value='Lunagent Mountain: Deepest Area')
    embed.add_field(name='Element', value='Dark', inline=True)
    embed.add_field(name='Base HP', value='530.000', inline=True)
    embed.add_field(name='Base EXP', value='6.300', inline=True)
    embed.add_field(name='P.Def', value='PH1: 274; PH2: 165', inline=True)
    embed.add_field(name='M.Def', value='PH1: 274; PH2: 165', inline=True)
    embed.add_field(name='P.Res', value='3', inline=True)
    embed.add_field(name='M.Res', value='3', inline=True)
    embed.add_field(name='Prorate', value='N:5  P:30  M:30', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='231', inline=True)
    embed.add_field(name='Retaliation', value="FS: 100% guard rate for 10 sec if inflicted during PH1 (Purple).\nFTS: 100% evasion rate for 10 sec if inflicted during PH2 (Red).\n\nWhen the boss's HP goes below 25%, the boss turns Red and switches to PH2.\nWhen the boss receives damage that is greater than 3% of its max HP, the boss's guard rate (PH1) or evasion rate (PH2) will increase to 100% for 10 sec.", inline=False)
    embed.add_field(name='Parts Destruction:', value='2 Parts: Left Hand (Evil Crystal Beast Claw, ARM), Chest (ADD)', inline=False)
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='cerberus')
async def cerberus(ctx):
    embed = discord.Embed(title='Cerberus')
    embed.add_field(name='MQ Chapter', value='5', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Spring of Rebirth: Top')
    embed.add_field(name='Element', value='BLUE: Water; RED: Fire; YELLOW: Wind; White: Neutral', inline=True)
    embed.add_field(name='Base HP', value='800.000', inline=True)
    embed.add_field(name='Base EXP', value='9.200', inline=True)
    embed.add_field(name='P.Def', value='N: 146; F: 970; T: 49; S: 97; LHP: 194', inline=True)
    embed.add_field(name='M.Def', value='N: 146; F: 970; T: 49; S: 97; LHP: 194', inline=True)
    embed.add_field(name='P.Res', value='N: 3; F: 50; T: 3; S: -5; LHP: 10', inline=True)
    embed.add_field(name='M.Res', value='N: 3; F: 50; T: 3; S: -5; LHP: 10', inline=True)
    embed.add_field(name='Prorate', value='N:15  P:20  M:15', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='145', inline=True)
    embed.add_field(name='Retaliation', value="F: Boss switches color to red (Fire element). In this state, the boss's def and physical resistance significantly increase, while\nits mdef and magical resistance significantly decrease\n T: Boss switches color to red (Fire element). In this state, the boss's mdef and magical resistance significantly increase, while\n its def and physical resistance significantly decrease.S: Boss switches color to yellow (Wind element) which decreases both its def/mdef and pres/mres.\n\nAfter 30 seconds of switching to red (Fire element) or yellow (Wind element), the boss will revert back to blue (Water element).\nWhen HP reaches below 25%, the boss switches color to white (Neutral element). From this point on, the boss can be FTS without any retaliation.TIPS: The non-tank party members should be aware of the tank's position at all times. This is a precaution just in case the boss performs the whole map, player-centered AOE, where the safe spot is at the tank's location.", inline=False)
    embed.add_field(name='Parts Destruction:', value='3 Parts:Head (Cerberus Head Crystal)\nLeft Shoulder\nRight Shoulder', inline=False)
    embed.set_image(url='https://images-ext-1.discordapp.net/external/VY4FHnY-iQO8QoAmABnVDMBDSaYEDPQAvymz2CcW5Cs/https/raw.githubusercontent.com/jrabella93/TSXen/main/images/boss/cerberus.png?quality=lossless&format=webp&width=540&height=270')
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='zolban', aliases=['zol'])
async def zolban(ctx):
    embed = discord.Embed(title='Zolban')
    embed.add_field(name='MQ Chapter', value='5', inline=True)
    embed.add_field(name='MQ Locked', value='Yes', inline=True)
    embed.add_field(name='Map', value='Dark Mirror')
    embed.add_field(name='Element', value='Wind', inline=True)
    embed.add_field(name='Base HP', value='244.000', inline=True)
    embed.add_field(name='Base EXP', value='3.900', inline=True)
    embed.add_field(name='P.Def', value='196', inline=True)
    embed.add_field(name='M.Def', value='382', inline=True)
    embed.add_field(name='P.Res', value='3', inline=True)
    embed.add_field(name='M.Res', value='3', inline=True)
    embed.add_field(name='Prorate', value='N:1  P:1  M:1', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='145', inline=True)
    embed.add_field(name='Retaliation', value="S: Retaliates with a foe-centered, fractional spikes AOE that inflicts Stop.\nT: Boss moves away", inline=False)
    embed.add_field(name='Parts Destruction:', value='2 Parts:\nBack/Crystal Wings (Magic Crystal Wing Fragment)\nTorso', inline=False)
    embed.set_image(url='https://raw.githubusercontent.com/jrabella93/TSXen/main/images/boss/zolban.png')
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

@bot.command(name='aranea', aliases=['ara'])
async def aranea(ctx):
    embed = discord.Embed(title='Aranea')
    embed.add_field(name='MQ Chapter', value='5', inline=True)
    embed.add_field(name='MQ Locked', value='No', inline=True)
    embed.add_field(name='Map', value='Garden of Sublimation: Central')
    embed.add_field(name='Element', value='Earth', inline=True)
    embed.add_field(name='Base HP', value='380.000', inline=True)
    embed.add_field(name='Base EXP', value='4.400', inline=True)
    embed.add_field(name='P.Def', value='PH1: 130; PH2: 120', inline=True)
    embed.add_field(name='M.Def', value='PH1: 110; PH2: 100', inline=True)
    embed.add_field(name='P.Res', value='4', inline=True)
    embed.add_field(name='M.Res', value='4', inline=True)
    embed.add_field(name='Prorate', value='N:10  P:20  M:15', inline=True)
    embed.add_field(name='Crit Res', value='0', inline=True)
    embed.add_field(name='Flee', value='PH1: 300; PH2: 375', inline=True)
    embed.add_field(name='Retaliation', value="None", inline=False)
    embed.add_field(name='Parts Destruction:', value='3 Parts:\nUpper Right Leg (HB),\nTorso (MD),\nLower Left Leg (Crystal Spider Leg Shell)', inline=False)
    embed.set_image(url='https://raw.githubusercontent.com/jrabella93/TSXen/main/images/boss/aranea.png')
    embed.set_footer(text='FTS = Flinch/Tumble/Stun\nEASY = 0.1 * def | flee\nHARD = 2 x def | flee\nNIGHTMARE = 4 x def | flee\nULTIMATE = 6 x def | flee.')
    await ctx.send(embed=embed)

token = os.getenv('DISCORD_TOKEN')
if not token:
    logging.error("Missing DISCORD_TOKEN in .env")
    exit(1)
logging.info(f"Bot token: {token[:5]}...")
bot.run(token)